version: "3.8"

services:
  # web:
  #   build:
  #     context: ../frontend/
  #     target: runner
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: production

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  ui:
    build:
      context: ../frontend/
      target: runner
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  pgadmin:
    image: dpage/pgadmin4
    restart: "always"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - "zitadel"

  db:
    restart: "always"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    networks:
      - "zitadel"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - "5432:5432"

networks:
  zitadel:

volumes:
  redis_data:
